// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2b3qFGPT09D3kxSabcf6AhGS-oo3wzxM',
    appId: '1:13613568006:android:9ee1f8d55d93265d687387',
    messagingSenderId: '13613568006',
    projectId: 'movie-diary-25',
    storageBucket: 'movie-diary-25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0msTDSliGnWojdoJwYUoQWvUcwM0ATak',
    appId: '1:13613568006:web:27d37dc3b286f6b1687387',
    messagingSenderId: '13613568006',
    projectId: 'movie-diary-25',
    authDomain: 'movie-diary-25.firebaseapp.com',
    storageBucket: 'movie-diary-25.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0msTDSliGnWojdoJwYUoQWvUcwM0ATak',
    appId: '1:13613568006:web:53d2d07f2fb065bf687387',
    messagingSenderId: '13613568006',
    projectId: 'movie-diary-25',
    authDomain: 'movie-diary-25.firebaseapp.com',
    storageBucket: 'movie-diary-25.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjJIKaSrwC9Lq5rloNjNTN8lFaIPq5dNA',
    appId: '1:13613568006:ios:0a1578203c3fdb9e687387',
    messagingSenderId: '13613568006',
    projectId: 'movie-diary-25',
    storageBucket: 'movie-diary-25.firebasestorage.app',
    iosBundleId: 'com.example.movdiary',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJIKaSrwC9Lq5rloNjNTN8lFaIPq5dNA',
    appId: '1:13613568006:ios:0a1578203c3fdb9e687387',
    messagingSenderId: '13613568006',
    projectId: 'movie-diary-25',
    storageBucket: 'movie-diary-25.firebasestorage.app',
    iosBundleId: 'com.example.movdiary',
  );

}